#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2016-12-10 15:35:03 +0000 (Sat, 10 Dec 2016)
#
#   
#
#   
#
#    to help steer this or other code I publish
#
#   
#

version: '2.1'
services:
  mesos:
    image: harisekhon/mesos:${VERSION:-latest}
    ports:
      - 5050:5050
      - 5051:5051
