#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2016-12-09 18:40:46 +0000 (Fri, 09 Dec 2016)
#
#   
#
#   
#
#    to help steer this or other code I publish
#
#   
#

version: '2.1'
services:
  consul-dev:
    image: harisekhon/consul-dev:${VERSION:-latest}
    ports:
      - 8500:8500
    command:
      consul agent -dev -data-dir /tmp -client 0.0.0.0
